[package]
name = "ojrs"
version = "0.1.0"
edition = "2021"
description = "Rust port of online-judge-tools/oj"
license = "MIT"

[[bin]]
name = "oj"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
command-group = "5"
cookie_store = { version = "0.21", features = ["serde_json"] }
dirs = "5"
dom_query = "0.27"
glob = "0.3"
rayon = "1"
regex = "1"
rpassword = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shlex = "1"
similar = "2"
tempfile = "3"
ureq = { version = "2", features = ["cookies"] }
url = "2"

[dev-dependencies]
indoc = "2"

[profile.release]
lto = true
codegen-units = 1
